services:
    db:
        image: mysql
        restart: always
        ports:
            - 3308:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: riwi_localstorage
            MYSQL_USER: root
